DROP TABLE IF EXISTS ACCOUNTS CASCADE;

CREATE TABLE IF NOT EXISTS ACCOUNTS
(
    ID LONG NOT NULL AUTO_INCREMENT,
    Number VARCHAR(255),
    ClientID INT NOT NULL,
    Balance DECIMAL(13,2) NOT NULL DEFAULT (0.00),
    IsOpen BOOLEAN DEFAULT (TRUE),
    PRIMARY KEY (Number),
    FOREIGN KEY (ClientID) REFERENCES CLIENTS(ID)
);

INSERT into ACCOUNTS(NUMBER, CLIENTID)  values ('12345678901234567890', 1);