DROP TABLE IF EXISTS CARDS CASCADE;

CREATE TABLE IF NOT EXISTS CARDS
(
    ID LONG NOT NULL AUTO_INCREMENT,
    Number VARCHAR(255) NOT NULL,
    AccountNumber VARCHAR(255) NOT NULL,
    ClientID INT NOT NULL,
    IsValid BOOLEAN DEFAULT (FALSE),
    PRIMARY KEY (Number),
    FOREIGN KEY (AccountNumber) REFERENCES ACCOUNTS(Number),
    FOREIGN KEY (ClientID) REFERENCES CLIENTS (ID)
);