DROP TABLE IF  EXISTS COUNTERPARTIES, CASCADE;

CREATE TABLE IF NOT EXISTS COUNTERPARTIES
(
    ID LONG NOT NULL AUTO_INCREMENT,
    CounterpartyID LONG,
    ClientID LONG,
    Surname VARCHAR(255),
    Name VARCHAR(255) NOT NULL,
    Patronymic VARCHAR(255),
    PhoneNumber VARCHAR(255) NOT NULL,
    FOREIGN KEY (ClientID) REFERENCES CLIENTS (ID)
);